[workspace]
resolver = "2"

members = [
    "keyvalues-serde",
    "keyvalues-parser",
]

exclude = [
    "parse-vdf-file",
]

[workspace.dependencies]
criterion = { version = "0.5.1", default-features = false }
insta = "1.39.0"
pretty_assertions = "1.4.0"
serde = "1.0.209"
