[package]
name = "parse-vdf-file"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
keyvalues-parser = { version = "0.1.0", path = "../keyvalues-parser" }
