[package]
name = "keyvalues-parser"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.56"

authors = ["Lovecraftian Horror <LovecraftianHorror@pm.me>"]
keywords = ["keyvalues", "vdf", "steam", "parser"]
description = "A parser/renderer for vdf text"
homepage = "https://github.com/lovecraftianhorror/vdf-rs"
repository = "https://github.com/lovecraftianhorror/vdf-rs"

[dependencies]
# TODO: switch parsing to `nom`
pest = "2.5"
pest_derive = "2.5"
# TODO: drop this
thiserror = "1.0.50"

[dev-dependencies]
criterion = { version = "0.4.0", default-features = false }
insta = "1.34.0"
pretty_assertions = "1.4.0"

[[bench]]
name = "parser"
harness = false
