[package]
name = "keyvalues-parser"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

authors = ["Lovecraftian Horror <LovecraftianHorror@pm.me>"]
keywords = ["keyvalues", "vdf", "steam", "parser"]
description = "A parser/renderer for vdf text"
homepage = "https://github.com/lovecraftianhorror/vdf-rs"
repository = "https://github.com/lovecraftianhorror/vdf-rs"

[dependencies]
pest = "2.1"
pest_derive = "2.1"
thiserror = "1.0.24"

[dev-dependencies]
criterion = "0.3.4"
insta = { version = "1.7.1", features = ["ron"] }
once_cell = "1.7"
pretty_assertions = "0.7.2"
serde = { version = "1.0.126", features = ["derive"] }

[[bench]]
name = "parser"
harness = false
