on: [push, pull_request]

name: "Build, Test, Format, and Lint"

jobs:
  multiple_toolchains:
    name: Multiple toolchain tasks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - 1.42.0

    steps:
      - uses: actions/checkout@v2

      - name: Install ${{ matrix.rust }} toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true

      # Uses `--all-targets` here to make sure that things like benchmarks
      # still compile
      - name: Check all targets
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-targets

      - name: Run the test suite
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Check formatting
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check clippy lints
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

  nightly_only:
    name: Nightly only tasks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      # Actually check the fuzzers so that they don't break silently
      - name: Check parser fuzzers
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path keyvalues-parser/fuzz/Cargo.toml
