on:
  push:
    branches:
    - main
  pull_request:
  schedule:
    # Run monthly to keep Rust toolchain changes fresh
    - cron: '0 0 1 * *'

name: "Build, Test, Format, and Lint"

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "--deny warnings"

jobs:
  multiple_toolchains:
    name: Multiple toolchain tasks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta

    steps:
      - uses: actions/checkout@v5

      - name: Install ${{ matrix.rust }} toolchain
        run: |
          rustup toolchain install ${{ matrix.rust }} --profile minimal --component clippy,rustfmt
          rustup default ${{ matrix.rust }}

      - name: Cache
        uses: Swatinem/rust-cache@v2

      # Uses `--all-targets` here to make sure that things like benchmarks
      # still compile
      - name: Check formatting
        run: |
          cargo fmt --all -- --check
      - name: Build all targets
        run: |
          cargo build --all-targets --all-features
      - name: Run the test suite
        run: |
          cargo test --all-features
          cargo bench -- --test
      - name: Check clippy lints
        run: |
          cargo clippy
      - name: Check docs
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc

  fuzz:
    name:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fuzzer:
          - '--fuzz-dir=keyvalues-parser/fuzz parse'
          - '--fuzz-dir=keyvalues-serde/fuzz serde'

    steps:
      - uses: actions/checkout@v5

      # Pin to a specific nightly version since we only want it for being able
      # to use unstable features, not because we _need_ the newest version.
      # This makes caching actually viable for more than just a day
      - name: Install nightly toolchain
        run: |
          rustup toolchain install --profile minimal nightly-2025-01-01
          rustup default nightly-2025-01-01
      
      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Run fuzzer
        run: |
          cargo --locked install cargo-fuzz
          cargo --locked fuzz run --jobs=4 ${{ matrix.fuzzer }} -- -max_total_time=120 -timeout=30
