on:
  push:
    paths:
      - "keyvalues-parser/src/**"
  pull_request:
    paths:
      - "keyvalues-parser/src/**"

name: Fuzz Parser

jobs:
  fuzz:
    name: "Fuzz (10 minutes)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-fuzz
      - name: Cargo Fuzz
        run: cargo fuzz run parse -- -max_total_time=600 -verbosity=0
        working-directory: keyvalues-parser
