# NOTE: The parser release and serde release workflow are nearly identical, so
# make sure to keep them in sync

name: Serde Release

on:
  push:
    tags:
      - 'serde-v*'

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: cargo test --all-features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --manifest-path keyvalues-serde/Cargo.toml

  release:
    needs: test

    name: Upload Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Publish serde library
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path keyvalues-serde/Cargo.toml --token ${{ secrets.CRATES_IO_TOKEN }}
