# NOTE: The parser release and serde release workflow are nearly identical, so
# make sure to keep them in sync

name: Parser Release

on:
  push:
    tags:
      - 'parser-v*'

jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Sanity check test run
        run: |
          cargo test --all-features --manifest-path keyvalues-parser/Cargo.toml

  release:
    needs: test

    name: Upload Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Publish parser library
        run: |
          cargo publish --manifest-path keyvalues-parser/Cargo.toml --token ${{ secrets.CRATES_IO_TOKEN }}
