on:
  push:
    paths:
      - ".github/workflows/ser_de_fuzzing.yml"
      - "keyvalues-serde/src/**"
      - "keyvalues-serde/fuzz/**"
  pull_request:
    paths:
      - ".github/workflows/ser_de_fuzzing.yml"
      - "keyvalues-serde/src/**"
      - "keyvalues-serde/fuzz/**"

name: Fuzz Ser De

jobs:
  run_ser_de_fuzzer:
    name: "Fuzz Ser De (5 minutes)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Nightly is needed for `cargo fuzz`
      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2021-06-01
          override: true

      - name: Get rustc version
        id: get-version
        run: |
          echo "::set-output name=version::$(rustc -V | sed 's/ /_/g')"

      - name: Cargo registry cache
        uses: actions/cache@v2
        with:
          path: ~/.cargo/registry
          key: run_ser_de_fuzzer-cargo-registry-${{ steps.get-version.outputs.version }}-1

      - name: Cargo build cache
        uses: actions/cache@v2
        with:
          path: keyvalues-serde/fuzz/target
          key: run_ser_de_fuzzer-cargo-build-${{ steps.get-version.outputs.version }}

      - name: Install cargo quickinstall
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-quickinstall

      - name: Install cargo fuzz
        uses: actions-rs/cargo@v1
        with:
          command: quickinstall
          args: cargo-fuzz

      - name: Run ser de fuzzer
        run: cargo fuzz run serde -- -max_total_time=300 -verbosity=0
        working-directory: keyvalues-serde
